### ISSUE TITLE
Reopen same solution removes it from oProjectExplorers collection

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#132]
Hi Doug,

Steps to reproduce:
1. Open a solution in Project Explorer
2. Without closing the first instance, open the same solution again

Observed behavior:
- There are 2 instances of Project Explorer open
- _SCREEN.oProjectExplorers.Count = 1
- Activating the first instance opened in Step 1 causes that Project Explorer instance to close with a message like this:
![image](https://user-images.githubusercontent.com/9847353/40244142-09686108-5a90-11e8-96d5-dd389246e90f.png)
- After the first instance closes, _SCREEN.oProjectExplorers.Count = 0, but the second instance of Project Explorer is still available.

The second instance seems to work fine yet, but this obviously presents a problem if you're trying to write a tool that's checking if there are any Project Explorer instances open.

Thanks,
Mike

**Comment by DougHennig** [comment]
The key for the Project Explorer instance in the collection is the path since there's only one solution per folder. Opening a second instance of the same solution opens a second Project Explorer but it fails silently adding it the collection because the key is the same.

What would you rather see happen in this case:

- Don't open the second instance of Project Explorer but simply activate the window for the existing one?
- Have both Project Explorers open and both in the collection, which means using a different key?

I can't see the utility of having the same solution open twice so I'm leaning toward the first but want your opinion.

Doug

**Comment by rschummer** [comment]
I can see benefit of using a second instance if you want to see different filters applied to the file list, and not have to keep switching between the two. 

I'm just not sure how this works with features that update the project file and keeping information in synch in the other Project Explorer instances of the same project.

**Comment by DougHennig** [comment]
I hadn't thought about keeping the two in sync -- that adds an extra layer of complexity. Leaning even more to the first one now.

**Comment by mikepotjer** [comment]
Personally, I would rather just keep it simple, and activate the existing window. VFP doesn't let you open multiple instances of the same .PJX (not even in separate VFP instances), so 2 instances of Project Explorer would need to share the same instance of a project object. If there are a number of developers that really want to compare different filters, as in Rick's use case, maybe that could be handled with some kind of export or reporting feature.

**Comment by DougHennig** [comment]
OK, try the latest build. I didn't update the Thor CFU files so you have to download it from here.

**Comment by mikepotjer** [comment]
It's working for me.
Thanks, Doug!
