### ISSUE TITLE
 Changing a .SC2 file outside the VFP9 x Commit File

### ISSUE THREAD

**Issue by DionisioSilvaJunior** [DougHennig/ProjectExplorer#138]
In sequence:

- Changing a .SC2 file outside the VFP9
- Refresh in TreeView
- The form name appears flaged correctly in the TreeView
- Position in form name in TreeView
- Right Click -> Commit File
- Describe the message to the Commit
- OK

A message appears:
![project explorer error](https://user-images.githubusercontent.com/39463259/40737228-8763a9c0-6416-11e8-86c7-6c95fe764a9f.PNG)

**Comment by DougHennig** [comment]
There are two issues here:

1. If you edit the SC2 file but not the SCX file, when you tell Project Explorer to commit the file, it regenerates the SC2 file because it assumes the SCX was changed. As a result, the change to the SC2 file is overwritten so when Project Explorer commits it, Git returns an error code indicating that there's nothing to commit. What you should do before committing the file is to right-click and choose Convert Text to Binary to regenerate the SCX file.
2. Project Explorer knows the commit failed but doesn't have an error message to display, which is why the message is blank. I'll fix that in a future release.
