### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#147]
Database Test with the Test table
Running Browse
We try to rename the test in test1
Error - file used
The table test was closed.
We are trying to rename again.
There is already a Table named test1
But path = test / test.dbf

**Comment by DougHennig** [comment]
For a table in a database, the Name property can be different than the Path property. Renaming a table in Project Explorer changes its Name property first then tries to rename the DBC, FPT, and CDX files (which affects the Path property). It could not do the latter because the table was in use. I will change Project Explorer to rename the files first so if it fails, the Name property is not changed.

In the mean time, you can use RENAME TABLE to change the Name property back to Test.
