### ISSUE TITLE
Error using messageboxex.prg

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#154]
If the project uses messageboxex and executes the application with the call of this program in the development environment, an error appears when trying to rebuild project.
![msg_err](https://user-images.githubusercontent.com/33526380/44622629-e131e500-a8c4-11e8-9691-4acc2f2c4393.JPG)

**Comment by DougHennig** [comment]
If you run your application from the Project Explorer, often you must close Project Explorer, use CLOSE ALL and CLEAR ALL, then reopen Project Explorer in order to build the project to avoid outstanding references. There is nothing I can do about that because using CLEAR ALL from within Project Explorer would kill it.
