### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#158]
Hi Doug,

Per our conversation at SWFox, allow selection of alternate PEX XML config files to allow easy switching of unrelated projects where the PJX might live in the same root folder.

Thanks.

**Comment by DougHennig** [comment]
Please grab the latest release (not added to Thor Updater yet) and try it out. It now works with solution files with an SLX extension so you can have more than one per folder. To create the first one, just open Project Explorer and choose a PJX when prompted. To create the second one, it's a little different because by default, if there's exactly one solution file in a folder, Project Explorer opens it. So, DO ProjectExplorer.app with '', .T. to force it to prompt you to pick a project so it can create a solution for that one too. Alternatively, you can open Project Explorer (which opens the first solution), then choose Open Solution from the menu and pick a different project to create the second solution.

Let me know if you run into any issues with these changes.

**Comment by rikaye** [comment]
Thanks, Doug! Will do.

**Comment by rikaye** [comment]
So far so good, Doug. For my particular environment, I know this will be helpful. Perhaps the option to pass an SLX filename as a parameter in addition to the prompt would be useful. Or maybe I should review the source code and see if you've already done that... :-)

**Comment by DougHennig** [comment]
Yes, you can pass it the name of an SLX file to open that solution.
