### ISSUE TITLE
Request: Can a PEx object survive a clear all, a la Thor?

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#176]
Thanks!

**Comment by DougHennig** [comment]
Not currently. I'll have to look into Thor to see how it handles this.

**Comment by DougHennig** [comment]
Thor doesn't actually survive CLEAR ALL; you can see that if you type WAIT WINDOW VARTYPE(_SCREEN.oThor) after CLEAR ALL. It looks like it does, though, because all of the Thor-related menu functions call a common dispatcher that instantiates Thor into _SCREEN.oThor if it isn't an object. With Project Explorer, there isn't a way to do CLEAR ALL (say from a program run from it) and have it stay open.
