### ISSUE TITLE
GIT Integration:  Add-in for auto-generation of binaries from updated text equivalent

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#179]
Now that I've had a bit of time to get more comfortable with how PEx integrates with Git, I've got a workflow question to put out there. It appears (quite logically) that PEx integrates with my local Git repo. It's up to me to interact with my remote repo outside of VFP and PEx. It appears that if another dev has pushed changes to the remote, I have to pull those changes to my local branch and manually generate the binaries from the text equivalents. It seems to me it should be possible to use an Add-in to see if the text equivalent is newer and then automatically update the local binary at the time I go to either edit or build. If this is a good assumption, the next question is has somebody already written this Add-in? Or perhaps it's already in Mike Potjer's VFPx Git tools?

TIA

**Comment by DougHennig** [comment]
The text equivalent will always be newer than the binary simply because it's generated after the binary is saved. One option would be to do a test: output each binary to a text file in a temp folder, compare that text file to the one in the dev folder (which may be newer due to a repository update; a simple comparison of checksums would be fine), and for any file where the comparison fails, regenerate the binary from the text file.

How does that sound?

**Comment by rikaye** [comment]
Much better than a timestamp, Doug. Is this a suggestion on how I can write this add-in or an offer? :-)

**Comment by Tracy-P** [comment]
I have been thinking of this for some time. I've been having trouble with that process. I have 644 binary files in my project folder that get changed by foxbin2prg. It takes over 2 minutes to process my project. (PEx takes over 20 seconds to open my project.)
I have been looking more at attempting to capture if changes have been made from the git responses more than the processing the project. 
Though I have thought about a second folder that holds the text equivalents and comparing checksums against those. There is always the possibility that second folder will be out of date somehow.

**Comment by DougHennig** [comment]
Thinking about this some more. I don't think we'd need to regen all the text files; theoretically, they'd all be there and current (if not, you can use FoxBin2PRG to create them). So, there are a couple of possibilities:

- Run a function that copies all text file to a temp folder. You'd need to do that BEFORE pulling/updating from the remote repo. Then do the pull/update. Then run another function that does the compare and generation of binaries from any changed text files.

- Do the pull/update then generate binaries from text files with today's date.

Thoughts? Any other ideas?

**Comment by rikaye** [comment]
Hi Doug,

HNY to you and yours! Sorry I let this sit for so long. I've been buried in some new stuff that I had to keep focused on.

I think I like option number 2. It seems like it would be the simplest approach as long as the assumption that the "today's date of the text file" rule holds true. As far as PeX is concerned, hooking this into the BeforeModifyFile(?) event would be good. 

It also occurs to me that something like this should also be called from a BeforeBuild event, although that feels like a separate use case which needs to be handled on its own, and is not PeX specific. Much like setting the recompile all option, maybe just automagically regenerating binaries when building would be another way to go for that situation. I've already got some build event code that turns off the readonly attribute (which I really can get rid of now that I'm out of VSS-one-developer-at-a-time mode).

**Comment by DougHennig** [comment]
I've been playing with this a bit and think I have a process that will work.

First, Project Explorer does a GIT FETCH to retrieve changes from the remote repository. It then does GIT DIFF --NAME-ONLY ORIGIN/MASTER to list the changed files from the fetch and saves that list. Then it does GIT MERGE FETCH_HEAD to merge the changes. You'll deal with any conflicts at this point.

Now it can go through the list of changed files and for any that are text equivalents, use FoxBin2PRG to convert them to binary. That way, it only uses FoxBin2PRG on the necessary files rather than all files.

One complication: if the merge fails because of a conflict (e.g. you and I both modified a form), then it can't do the last step, or it could but you'll have to regenerate the binaries from the merged files yourself.

Thoughts?

**Comment by DougHennig** [comment]
I added Update from Remote Repository, Push to Remote Repository, and Resolve Conflict functions to the shortcut menu that implement these ideas. If a conflict occurs during the merge, the TortoiseGit conflict dialog appears (or you're told about the conflict if TortoiseGit isn't installed).
