### ISSUE TITLE
First run on a folder structure

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#183]
If I run Project Explorer the first time in a given folder, it asks for _solution.xml_.  

There is none. The dialog looks like a **PUTFILE**, but it does not create a file in the location I select.
The the dialog is a **PUTFILE**. But it does not create a file.

Then the documentation stats, that a dialog to pick a _PJX_ should be displayed. It is not.
I know I can select PJX from the initial **PUTFILE**. This is not intuitive.

So, for me, the workflow (no parameters given) would be:
- locate a _solution.xml_, use if found
- if not found, ask for a location of _solution.xml_ (**PUTFILE**)
- if not aborted, look (**GETFILE**) for a _PJX_
- open Project Explorer empty (no _PJX_ selected) or with  given _PJX_

Note:
- Thor is not used 
- the place I like to place the _solution.xml_ does not  hold a _PJX_. The default path does not hold a _PJX_ nor should it hold the _solution.xml_
- the PATH holds neither _solution.xml_ nor a _PJX_

**Comment by lscheffler** [comment]
Ooops. Looks like the docu needs some update on that. If I pick a project _xyz.pjx_ it creates a _xyz.slx_.   
This looks like the solution file - but it's now a name I would not have picked. I can rename it on file level, no doubt. Anyway this is odd. It should ask for a name.

Additional: The _Open Solution_  menu item from the hamburger menu raises a **PUTFILE** dialogue (its named OPEN) with _Solution.xml_ as file name. The dialogue also allow to open _PJX_. This is confusing. It looks like the same logic as on run_without_parameter.
It's an odd open / new logic. I see what you like to achieve, and it's fine for a single project logic, but somehow it's not what I suspect to happen if a read "SAVE" on a file dialogue.

**Comment by DougHennig** [comment]
The documentation is correct. The logic is:

* If a single solution file exists in the current folder, it’s opened automatically.
* If a single project file exists in the current folder, a solution file is automatically created for it and opened.
* Otherwise, it displays a dialog prompting you to select a solution or a PJX file. The solution can either be Solution.xml (the older name, if it exists) or the new name: the project with an SLX extension. The name has to be one or the other; it doesn't allow you to name the file yourself or else the first item in this logic won't work.

The Open Solution function runs the same method as executes at startup so it does the same thing.
