### ISSUE TITLE
Drop classes into a grid column

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#34]
It would be really handy to be able to drag a class from the ProjectExplorer, and drop it on a grid column, and have the class added to the column. If the default Text1 control still exists, display a prompt asking the user whether to remove the Text1 control and replace it with the class that was dropped on the column. The VFP Toolbox has this feature, as does the Finder tool available through Thor, so the source code to do this can be obtained from either tool. The code that Finder uses is in the custDragDrop class of Thor_Proc_Finder.VCX, found in the folder Thor\Tools\Procs.

**Comment by DougHennig** [comment]
Thanks for pointing me in the right direction. Added in the latest build. One thing to note: I'm using OLE drag and drop rather than native, and it works a little differently. You have to select the column in the Properties window first then drag the class to the column in the form; otherwise, it doesn't work correctly (it adds a label to the form due to the way OLE drag and drop works).

**Comment by mikepotjer** [comment]
Thanks Doug. This feature is working as described, but it seems that this change broke the previous drag and drop behavior. If I drag a class anywhere OTHER THAN a selected grid column, all I get is a label with the caption set to the class name. I reset my ProjectExplorer branch to the previous commit and tested dragging the same class onto the form, and the control was added as expected (not the label).

**Comment by DougHennig** [comment]
OK, try the new build I just pushed.

**Comment by mikepotjer** [comment]
Looks like that fixed it. I tried dragging a class onto the form surface, onto a page, onto a Container class on the form, and all is working as expected.

**Comment by DougHennig** [comment]
Thanks,
