### ISSUE TITLE
Class properties

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#68]
In general, there is no need to disable the Class / Classlibrary / BaseClass / IncludeFile / OLE Public properties of a class from edit. Ok it might need a COMPILE CLASSLIB after save and the user need to know what he does. Kind of expert mode?
The /*Class/* stuff might be picked via AGETCLASS() or not.

The icons, otoh, might be changed freely. Double click on the icon or the like.

**Comment by DougHennig** [comment]
Changing those things requires hacking the VCX. Since they are easily changed by editing the class and choosing Class Info from the Class menu, I do not see a need to do it in Project Explorer since those are really class editing tasks.

**Comment by lscheffler** [comment]
Only native way to change baseclass is via ClassBrowser.

And if there is something I hate it's
Creating a class
pick header
pick icons
add comment

This is clicking through endless forms ....

And I wouldn't call it hacking the VCX. This is editing it. Hacking is BROWSE. ;)

Think about how to hook into
-the properties mask
-new class dialogue for this. Not urgend

**Comment by DougHennig** [comment]
The latest release allows you to edit the OLEPublic setting and the icons for a class. It's better to change the include file for the class in the Class Designer since recompiling the VCX is necessary and that may not be possible (you may have another class in the VCX open in the Class Designer, for example). I'll create an issue to create an add-in that allows changing the class for a form or class.
