### ISSUE TITLE
Raise autocommit (addin) for files changed

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#80]
It looks like the projectexplorer is able to detect file changes, at least for source control on. (I have not tested but icons where changed on the conference)
If this is detected a addin could be called to fire automatic commits.

**Comment by DougHennig** [comment]
You can use the AfterModifyItem addin. It's passed a reference to the item (ProjectItem subclass) that was modified. I think you may also need a reference to the form so you can do something like loForm.oSolution.CommitItems(message, array of file names), so I added that as another parameter.

However, given that Project Explorer support auto-commits with #79 discussing what to do about the commit message, I think this issue can be closed).

**Comment by lscheffler** [comment]
AfterModifyItem.
Do you check some VFP Windows or do you eventbind to file system? I use config.fpw _TEDIT_ ....
Also a simple save without closing should fire. :)

**Comment by DougHennig** [comment]
Project Explorer uses Windows event binding to bind to the destroy event of the editor window. So, it likely won't work with TEDIT because it won't know how to get the handle of that window. Save without closing doesn't fire the event because it's not looking at the file, only the window. I guess this could be changed to bind to the file changed event instead but that might be more complex.

**Comment by lscheffler** [comment]
Put it under _wishes, we dream off_.
